(function() {var implementors = {};
implementors["shiplift"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://doc.rust-lang.org/rustc-serialize/rustc_serialize/json/enum.ParserError.html\" title=\"enum rustc_serialize::json::ParserError\">ParserError</a>&gt; for <a class=\"enum\" href=\"shiplift/errors/enum.Error.html\" title=\"enum shiplift::errors::Error\">Error</a>",synthetic:false,types:["shiplift::errors::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://doc.rust-lang.org/rustc-serialize/rustc_serialize/json/enum.DecoderError.html\" title=\"enum rustc_serialize::json::DecoderError\">DecoderError</a>&gt; for <a class=\"enum\" href=\"shiplift/errors/enum.Error.html\" title=\"enum shiplift::errors::Error\">Error</a>",synthetic:false,types:["shiplift::errors::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://doc.rust-lang.org/rustc-serialize/rustc_serialize/json/enum.EncoderError.html\" title=\"enum rustc_serialize::json::EncoderError\">EncoderError</a>&gt; for <a class=\"enum\" href=\"shiplift/errors/enum.Error.html\" title=\"enum shiplift::errors::Error\">Error</a>",synthetic:false,types:["shiplift::errors::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"enum\" href=\"https://docs.rs/hyper/v0.10.13/hyper/error/enum.Error.html\" title=\"enum hyper::error::Error\">HttpError</a>&gt; for <a class=\"enum\" href=\"shiplift/errors/enum.Error.html\" title=\"enum shiplift::errors::Error\">Error</a>",synthetic:false,types:["shiplift::errors::Error"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/convert/trait.From.html\" title=\"trait core::convert::From\">From</a>&lt;<a class=\"struct\" href=\"https://doc.rust-lang.org/nightly/std/io/error/struct.Error.html\" title=\"struct std::io::error::Error\">IoError</a>&gt; for <a class=\"enum\" href=\"shiplift/errors/enum.Error.html\" title=\"enum shiplift::errors::Error\">Error</a>",synthetic:false,types:["shiplift::errors::Error"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
